theme: jekyll-theme-hacker
title: Cyclic Immunofluorescence
description: A DIY Approach to Highly Multiplexed Cell and Tissue Imaging
sass:
    load_paths:
        - _scss
        - node_modules
plugins:
    - jekyll-redirect-from
exclude: []

baseurl: '/cycif'